# Generated by Django 4.0.4 on 2022-04-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('Region', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('ItemType', models.CharField(max_length=50)),
                ('SalesChannel', models.CharField(max_length=100)),
                ('OrderPriority', models.CharField(max_length=100)),
                ('OrderDate', models.CharField(max_length=100)),
                ('OrderID', models.CharField(max_length=100)),
                ('ShipDate', models.CharField(max_length=100)),
                ('UnitsSold', models.CharField(max_length=100)),
                ('UnitPrice', models.CharField(max_length=100)),
                ('UnitCost', models.CharField(max_length=100)),
                ('TotalRevenue', models.CharField(max_length=100)),
                ('TotalCost', models.CharField(max_length=100)),
                ('TotalProfit', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
